build_and_deploy:
  image: docker:stable
  stage: build
  script:
    - docker image build --no-cache --pull -t jaedle/docker-rpi-monitor:latest .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker image push jaedle/docker-rpi-monitor:latest
  only:
    - main